apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kdvops-vs
  namespace: kdvops-ns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: web.kdvops.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
spec:
  hosts:
  - "web.kdvops.com"
  gateways:
  - istio-system/kdvops-gateway
  http:
  - route:
    - destination:
        host: kdvops-web-svc
        port:
          number: 80
