apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kdvops.fullname" . }}-pvc
spec:
  accessModes: ["ReadWriteMany"]
  resources: { requests: { storage: 1Gi } }
  storageClassName: ""
  volumeName: {{ include "kdvops.fullname" . }}-pv